/**
  ******************************************************************************
  * @file           : board.c
  * @brief          : the board class interface
  ******************************************************************************
  STM32CubeMX Configuration

  USART1: Mode Asynchronous.
  DMA Settings:
    Add USART1_TX (Stream 7, Channel 4). Mode: Normal, Increment Address: Memory.
    Add USART1_RX (Stream 5, Channel 4). Mode: Circular (best for continuous data), Increment Address: Memory.
  NVIC Settings: Enable USART1 global interrupt.
  ******************************************************************************
  */
#include <stdio.h>

#include "main.h"
#include "cmsis_os.h"

#include "uart.h"
#include "pwm.h"
#include "led.h"
#include "readline.h"
#include "platform.h"
#include "command.h"
#include "board.h"

/* globals from main.c which generated by CubeMX */
extern  TIM_HandleTypeDef       htim1;
extern  TIM_HandleTypeDef       htim8;
extern	UART_HandleTypeDef	hlpuart1;
extern	UART_HandleTypeDef	huart4;
extern	osThreadId_t		defaultTaskHandle;
extern	osThreadId_t		consoleTaskHandle;
extern	osThreadId_t		modbusTaskHandle;


uint32_t        stat_tmr1_cc;		/* for debugging timer1 */
uint32_t        stat_tmr1_chan[4];

pwm_t   *pwmaster;


typedef	union	{        /* serial port compound structure */
	rdln_t	readline;
	mbus_t	mbus;
} spc_t;

/* generic LPUART1 for debug / update / modbus protocol testing */
static	uart_t	conuart;
static	spc_t	conattr;
xtcb_t  console;

/* RS485 USART4 for production connection / update / modbus protocol */
static	uart_t	mbuart;
static  spc_t	mbattr;
xtcb_t  modbus;

char	*splash = "\r\n\
__________  __      __  _____                  .__  .__                \r\n\
|______   |/  \\    /  \\/     \\     ____   ____ |  | |__| ____   ____   \r\n\
 |     ___/\\   \\/\\/   /  \\ /  \\   /  _ \\ /    \\|  | |  |/    \\_/ __ \\  \r\n\
 |    |     \\        /    Y    \\ (  <_> )   |  \\  |_|  |   |  \\  ___/      \r\n\
 |____|      \\__/\\  /\\____|__  /  \\____/|___|  /____/__|___|  /\\___  >    \r\n\
                  \\/         \\/              \\/             \\/     \\/     \r\n\
\r\n\
CLI ready. Type 'help' for commands.\r\n#> ";



/**
 * @brief  Called when DMA finishes sending data
 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart) 
{
	bai_uart_send_awake(huart);
}

/**
 * @brief  Called when DMA finishes receiving the specified number of bytes
 */
void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size)
{
	if (Size) {
		bai_uart_receive_awake(huart, Size);
	}
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
	xtcb_t	*xtcb = bai_get_uart_xtcb(huart);
	uart_t	*ufp = xtcb->uart;

	if (huart->ErrorCode & HAL_UART_ERROR_ORE) {
		__HAL_UART_CLEAR_OREFLAG(huart);	/* clear ORE, NE, FE flags */

		/* reset the state machine in the HAL, otherwise the next
		 * call would return HAL_BUSY */
		huart->RxState = HAL_UART_STATE_BUSY_RX;
		huart->ErrorCode = HAL_UART_ERROR_NONE;

		/* check if the DMA still functional. 
		 * In Circular mode, DMA doesn't need to restart */
		/*if (!(huart->hdmarx->Instance->CR & DMA_SxCR_EN)) {
			huart->hdmarx->Instance->CR |= DMA_SxCR_EN;
		}*/

		if (ufp->state & FCMD_SEND) {
			bai_uart_send_awake(huart);
		}
		if (ufp->state & FCMD_RECV) {
			bai_uart_receive_awake(huart, -1);
		}
	}
}

void bai_uart_reset(void *huart)
{
	UART_HandleTypeDef	*hp = huart;

	/* enforce a full stop of UART DMA */
	HAL_UART_DMAStop(hp);

	/* reset UART peripheral, clean all register status and error flags.
	 * almost same to power off/on the UART hardware */
	__HAL_RCC_USART1_FORCE_RESET();
	HAL_Delay(1);	/* delay for the reset */
	__HAL_RCC_USART1_RELEASE_RESET();

	/* a copy of the initialization function generated by CubeMX */
	hp->Init.BaudRate = 115200;
	hp->Init.WordLength = UART_WORDLENGTH_8B;
	hp->Init.StopBits = UART_STOPBITS_1;
	hp->Init.Parity = UART_PARITY_NONE;
	hp->Init.Mode = UART_MODE_TX_RX;
	hp->Init.HwFlowCtl = UART_HWCONTROL_NONE;
	hp->Init.OverSampling = UART_OVERSAMPLING_16;
	HAL_UART_Init(hp);
}

int bai_uart_dma_receive(void *huart, char *rx_ring, int rx_len)
{
	UART_HandleTypeDef	*hp = huart;

	/* disabling half‑transfer interrupt avoids useless interrupts. */
	__HAL_DMA_DISABLE_IT(hp->hdmarx, DMA_IT_HT);
	return HAL_UARTEx_ReceiveToIdle_DMA(huart, (uint8_t *)rx_ring, rx_len);
}

int bai_uart_dma_index(void *huart, int rx_len)
{
	UART_HandleTypeDef	*hp = huart;

	return rx_len - __HAL_DMA_GET_COUNTER(hp->hdmarx);
}

int bai_uart_dma_send(void *huart, char *tx_buf, int tx_len)
{
	return HAL_UART_Transmit_DMA(huart, (uint8_t *)tx_buf, tx_len);
}

int bai_uart_poll_try(void *huart)
{
	uint8_t	ch;

	if (__HAL_UART_GET_FLAG((UART_HandleTypeDef*)huart, UART_FLAG_RXNE) == SET) {
		HAL_UART_Receive(huart, &ch, 1, HAL_MAX_DELAY);
		return (int) ch;
	}
	return -1;
}

int bai_uart_poll_receive(void *huart, char *rx_buf, int rx_len)
{
	while (rx_len) {
		if (__HAL_UART_GET_FLAG((UART_HandleTypeDef*)huart, UART_FLAG_RXNE) == SET) {
			HAL_UART_Receive(huart, (uint8_t*)rx_buf++, 1, HAL_MAX_DELAY);
			rx_len--;
		}
	}
	return rx_len;
}

int bai_uart_poll_send(void *huart, char *tx_buf, int tx_len)
{
	return HAL_UART_Transmit(huart, (uint8_t *)tx_buf, (uint16_t)tx_len, HAL_MAX_DELAY);
}

void bai_led_on(void *gpio, int pin)
{
	HAL_GPIO_WritePin(gpio, pin, GPIO_PIN_SET);
}

void bai_led_off(void *gpio, int pin)
{
	HAL_GPIO_WritePin(gpio, pin, GPIO_PIN_RESET);
}

void bai_spin_lock(void)
{
	__disable_irq();
}

void bai_spin_unlock(void)
{
	__enable_irq();
}

void bai_soft_delay(int ms)
{
	osDelay(ms);
}

void bai_hard_delay(int ms)
{
	HAL_Delay(ms);
}

void *bai_get_uart_xtcb(void *huart)
{
	if (console.uart->handler == huart) {
                return &console;
        }
	if (modbus.uart->handler == huart) {
		return &modbus;
	}
	return NULL;
}

void *bai_get_current_xtcb(void)
{
	osThreadId_t self = osThreadGetId();

	if (console.taskid == self) {
		return &console;
	}
	if (modbus.taskid == self) {
		return &modbus;
	}
	return &console;	/* set defaults to console */
}

void *bai_get_default_uart(void)
{
	return &console;
}

int bai_uart_send_sleep(void *uhandle, int ms)
{
	uart_t	*ufp = uhandle;
	uint32_t  rc;

	if ((ufp->taskid = osThreadGetId()) != NULL) {
		rc = ulTaskNotifyTake(pdTRUE, 
				ms == 0 ? portMAX_DELAY : pdMS_TO_TICKS(ms));
		if (rc <= 0) {
			return -1;	/* timeout */
		}
		return 0;	/* wake up by ISR */
	}

	if (ms == 0) {	/* infinite sleep */
		while (ufp->state & FCMD_SEND) osDelay(1);
	} else {
		while (ms-- && (ufp->state & FCMD_SEND)) osDelay(1);
	}
	if (ufp->state & FCMD_SEND) {
		return -1;	/* timeout */
	}
	return 0;	/* wake up by ISR */
}

void bai_uart_send_awake(void *huart)
{
	BaseType_t	xHigherWoken = pdFALSE;
	xtcb_t		*xtcb = bai_get_uart_xtcb(huart);
	
	xtcb->uart->state &= ~FCMD_SEND;
	if (xtcb->uart->taskid) {
		vTaskNotifyGiveFromISR(xtcb->uart->taskid, &xHigherWoken);
		portYIELD_FROM_ISR(xHigherWoken);
	}
}

int bai_uart_receive_sleep(void *uhandle, int ms)
{
	uart_t  *ufp = uhandle;
	xtcb_t	*xtcb = bai_get_uart_xtcb(ufp->handler);
	uint32_t  rc;

	if (xtcb->taskid) {
		rc = ulTaskNotifyTake(pdTRUE,
				ms == 0 ? portMAX_DELAY : pdMS_TO_TICKS(ms));
		if (rc <= 0) {
			return -1;	/* timeout */
		}
		return 0;	/* wake up by ISR */
	}

	if (ms == 0) {	/* infinite sleep */
		while (ufp->state & FCMD_RECV) osDelay(1);
	} else {
		while (ms-- && (ufp->state & FCMD_RECV)) osDelay(1);
	}
	if (ufp->state & FCMD_RECV) {
		return -1;	/* timeout */
	}
	return 0;	/* wake up by ISR */
}

void bai_uart_receive_awake(void *huart, int state)
{
	BaseType_t	xHigherWoken = pdFALSE;
	xtcb_t		*xtcb = bai_get_uart_xtcb(huart);
	
	if (xtcb->uart->state & FCMD_RECV) {
		if (state < 0) {
			xtcb->uart->state &= ~FCMD_RECV;
		}
		if (xtcb->taskid) {
			vTaskNotifyGiveFromISR(xtcb->taskid, &xHigherWoken);
		}
		portYIELD_FROM_ISR(xHigherWoken);
	}
}


int board_init(void)
{
	/* initialize the console for user interface
	 * Note: tcb not ready at this moment so this line in invalid:
	 *   console.taskid = consoleTaskHandle; 
	 */
	console.uartid   = &hlpuart1;
	console.uart     = &conuart;
	console.readline = &conattr.readline;
	console.mbus     = &conattr.mbus;
	uart_init(console.uart, console.uartid);
	readline_init(console.readline, console.uart);

	/* initialize the modbus port for industrial interface */
	modbus.uartid   = &huart4;
	modbus.uart     = &mbuart;
	modbus.readline = &mbattr.readline;
	modbus.mbus     = &mbattr.mbus;
	uart_init(modbus.uart, modbus.uartid);
	readline_init(modbus.readline, modbus.uart);

	//bai_uart_poll_send(&hlpuart1, "HelloWorld\r\n", 12);
	//bai_uart_poll_send(&huart4, "HelloWorld\r\n", 12);


	//led_init(GPIO_PIN_5);

	__HAL_TIM_ENABLE_IT(&htim1, TIM_IT_BREAK);
	__HAL_TIM_ENABLE_IT(&htim8, TIM_IT_BREAK);

	//pwmaster = pwm_init(&htim1, NULL, PWM_MODE_ASYINT | PWM_MODE_RESTRICT);
	pwmaster = pwm_init(&htim1, NULL, PWM_MODE_DUAL | PWM_MODE_RESTRICT | PWM_MODE_MULTIDUTY);
	pwm_open(pwmaster, 100000, 20, 100);
	pwm_start(pwmaster);

	command_init(&console);
	//cli_init(&modbus, NULL);
	command_init(&modbus);
	return 0;
}

void panic(void *p)
{ 
	static uint8_t  dying[] = { "BOM!!!\r\n" };
        
	if (p == NULL) {
                HAL_UART_Transmit(&hlpuart1, dying, 8, HAL_MAX_DELAY);
                HAL_UART_Transmit(&huart4, dying, 8, HAL_MAX_DELAY);
        }
} 

