/**
  ******************************************************************************
  * @file           : board.c
  * @brief          : the board class interface
  ******************************************************************************
  STM32CubeMX Configuration

  USART1: Mode Asynchronous.
  DMA Settings:
    Add USART1_TX (Stream 7, Channel 4). Mode: Normal, Increment Address: Memory.
    Add USART1_RX (Stream 5, Channel 4). Mode: Circular (best for continuous data), Increment Address: Memory.
  NVIC Settings: Enable USART1 global interrupt.
  ******************************************************************************
  */
#include <stdio.h>
#include "main.h"

extern void uart_write_unblock(void *huart);
extern void uart_read_unblock(void *huart);


/**
 * @brief  Called when DMA finishes sending data
 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart) 
{
	uart_write_unblock(huart);
}

/**
 * @brief  Called when DMA finishes receiving the specified number of bytes
 */
/*
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) 
{
	uart_read_unblock(huart);
}
*/

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
	if (huart->ErrorCode & HAL_UART_ERROR_ORE) {
		__HAL_UART_CLEAR_OREFLAG(huart);	/* clear ORE, NE, FE flags */

		/* reset the state machine in the HAL, otherwise the next
		 * call would return HAL_BUSY */
		huart->RxState = HAL_UART_STATE_BUSY_RX;
		huart->ErrorCode = HAL_UART_ERROR_NONE;

		/* check if the DMA still functional. 
		 * In Circular mode, DMA doesn't need to restart */
		if (!(huart->hdmarx->Instance->CR & DMA_SxCR_EN)) {
			huart->hdmarx->Instance->CR |= DMA_SxCR_EN;
		}
	}
}

void bai_uart_reset(void *huart)
{
	UART_HandleTypeDef	*hp = huart;

	/* enforce a full stop of UART DMA */
	HAL_UART_DMAStop(hp);

	/* reset UART peripheral, clean all register status and error flags.
	 * almost same to power off/on the UART hardware */
	__HAL_RCC_USART1_FORCE_RESET();
	HAL_Delay(1);	/* delay for the reset */
	__HAL_RCC_USART1_RELEASE_RESET();

	/* a copy of the initialization function generated by CubeMX */
	hp->Init.BaudRate = 115200;
	hp->Init.WordLength = UART_WORDLENGTH_8B;
	hp->Init.StopBits = UART_STOPBITS_1;
	hp->Init.Parity = UART_PARITY_NONE;
	hp->Init.Mode = UART_MODE_TX_RX;
	hp->Init.HwFlowCtl = UART_HWCONTROL_NONE;
	hp->Init.OverSampling = UART_OVERSAMPLING_16;
	HAL_UART_Init(hp);
}

int bai_uart_dma_receive(void *huart, char *rx_ring, int rx_len)
{
	return HAL_UART_Receive_DMA(huart, (uint8_t *)rx_ring, rx_len);
}

int bai_uart_dma_index(void *huart, int rx_len)
{
	UART_HandleTypeDef	*hp = huart;

	return rx_len - __HAL_DMA_GET_COUNTER(hp->hdmarx);
}

int bai_uart_dma_send(void *huart, char *tx_buf, int tx_len)
{
	return HAL_UART_Transmit_DMA(huart, (uint8_t *)tx_buf, tx_len);
}

int bai_uart_poll_try(void *huart)
{
	uint8_t	ch;

	if (__HAL_UART_GET_FLAG((UART_HandleTypeDef*)huart, UART_FLAG_RXNE) == SET) {
		HAL_UART_Receive(huart, &ch, 1, HAL_MAX_DELAY);
		return (int) ch;
	}
	return -1;
}

int bai_uart_poll_receive(void *huart, char *rx_buf, int rx_len)
{
	while (rx_len) {
		if (__HAL_UART_GET_FLAG((UART_HandleTypeDef*)huart, UART_FLAG_RXNE) == SET) {
			HAL_UART_Receive(huart, (uint8_t*)rx_buf++, 1, HAL_MAX_DELAY);
			rx_len--;
		}
	}
	return rx_len;
}

int bai_uart_poll_send(void *huart, char *tx_buf, int tx_len)
{
	return HAL_UART_Transmit(huart, (uint8_t *)tx_buf, (uint16_t)tx_len, HAL_MAX_DELAY);
}

void bai_led_on(void *gpio, int pin)
{
	HAL_GPIO_WritePin(gpio, pin, GPIO_PIN_SET);
}

void bai_led_off(void *gpio, int pin)
{
	HAL_GPIO_WritePin(gpio, pin, GPIO_PIN_RESET);
}

void bai_spin_lock(void)
{
}

void bai_spin_unlock(void)
{
}



