/**
  ******************************************************************************
  * @file           : board.c
  * @brief          : the board class interface
  ******************************************************************************
  STM32CubeMX Configuration

  USART1: Mode Asynchronous.
  DMA Settings:
    Add USART1_TX (Stream 7, Channel 4). Mode: Normal, Increment Address: Memory.
    Add USART1_RX (Stream 5, Channel 4). Mode: Circular (best for continuous data), Increment Address: Memory.
  NVIC Settings: Enable USART1 global interrupt.
  ******************************************************************************
*/

#include <stdio.h>
#include "main.h"
#include "board_stm32f4xx.h"
#include "uart.h"
#include "led.h"
#include "readline.h"
#include "platform.h"
#include "superloop.h"

extern	UART_HandleTypeDef	huart1;

static	uart_t	conuart;
static	rdln_t	conreadln;
static	xtcb_t	console;

char	*splash = "\r\n\
STM32 Time-Triggered Co-operative Super-Loop.\r\n\
#> ";


/**
 * @brief  Called when DMA finishes sending data
 */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart) 
{
	bai_uart_send_awake(huart);
}

/**
 * @brief  Called when DMA finishes receiving the specified number of bytes
 */
void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size)
{
	if (Size) {
		bai_uart_receive_awake(huart, Size);
	}
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
	xtcb_t	*xtcb = bai_get_uart_xtcb(huart);
	uart_t	*ufp = xtcb->uart;

	if (huart->ErrorCode & HAL_UART_ERROR_ORE) {
		__HAL_UART_CLEAR_OREFLAG(huart);	/* clear ORE, NE, FE flags */

		/* reset the state machine in the HAL, otherwise the next
		 * call would return HAL_BUSY */
		huart->RxState = HAL_UART_STATE_BUSY_RX;
		huart->ErrorCode = HAL_UART_ERROR_NONE;

		/* check if the DMA still functional. 
		 * In Circular mode, DMA doesn't need to restart */
		/*if (!(huart->hdmarx->Instance->CR & DMA_SxCR_EN)) {
			huart->hdmarx->Instance->CR |= DMA_SxCR_EN;
		}*/

		if (ufp->state & FCMD_SEND) {
			bai_uart_send_awake(huart);
		}
		if (ufp->state & FCMD_RECV) {
			bai_uart_receive_awake(huart, -1);
		}
	}
}

void bai_uart_reset(void *huart)
{
	UART_HandleTypeDef	*hp = huart;

	/* enforce a full stop of UART DMA */
	HAL_UART_DMAStop(hp);

	/* reset UART peripheral, clean all register status and error flags.
	 * almost same to power off/on the UART hardware */
	__HAL_RCC_USART1_FORCE_RESET();
	HAL_Delay(1);	/* delay for the reset */
	__HAL_RCC_USART1_RELEASE_RESET();

	/* a copy of the initialization function generated by CubeMX */
	hp->Init.BaudRate = 115200;
	hp->Init.WordLength = UART_WORDLENGTH_8B;
	hp->Init.StopBits = UART_STOPBITS_1;
	hp->Init.Parity = UART_PARITY_NONE;
	hp->Init.Mode = UART_MODE_TX_RX;
	hp->Init.HwFlowCtl = UART_HWCONTROL_NONE;
	hp->Init.OverSampling = UART_OVERSAMPLING_16;
	HAL_UART_Init(hp);
}

int bai_uart_dma_receive(void *huart, char *rx_ring, int rx_len)
{
	UART_HandleTypeDef	*hp = huart;

	/* disabling half‑transfer interrupt avoids useless interrupts. */
	__HAL_DMA_DISABLE_IT(hp->hdmarx, DMA_IT_HT);
	return HAL_UARTEx_ReceiveToIdle_DMA(huart, (uint8_t *)rx_ring, rx_len);
}

int bai_uart_dma_index(void *huart, int rx_len)
{
	UART_HandleTypeDef	*hp = huart;

	return rx_len - __HAL_DMA_GET_COUNTER(hp->hdmarx);
}

int bai_uart_dma_send(void *huart, char *tx_buf, int tx_len)
{
	return HAL_UART_Transmit_DMA(huart, (uint8_t *)tx_buf, tx_len);
}

int bai_uart_poll_try(void *huart)
{
	uint8_t	ch;

	if (__HAL_UART_GET_FLAG((UART_HandleTypeDef*)huart, UART_FLAG_RXNE) == SET) {
		HAL_UART_Receive(huart, &ch, 1, HAL_MAX_DELAY);
		return (int) ch;
	}
	return -1;
}

int bai_uart_poll_receive(void *huart, char *rx_buf, int rx_len)
{
	while (rx_len) {
		if (__HAL_UART_GET_FLAG((UART_HandleTypeDef*)huart, UART_FLAG_RXNE) == SET) {
			HAL_UART_Receive(huart, (uint8_t*)rx_buf++, 1, HAL_MAX_DELAY);
			rx_len--;
		}
	}
	return rx_len;
}

int bai_uart_poll_send(void *huart, char *tx_buf, int tx_len)
{
	return HAL_UART_Transmit(huart, (uint8_t *)tx_buf, (uint16_t)tx_len, HAL_MAX_DELAY);
}

void bai_led_on(void *gpio, int pin)
{
	HAL_GPIO_WritePin(gpio, pin, GPIO_PIN_SET);
}

void bai_led_off(void *gpio, int pin)
{
	HAL_GPIO_WritePin(gpio, pin, GPIO_PIN_RESET);
}

void bai_spin_lock(void)
{
	__disable_irq();
}

void bai_spin_unlock(void)
{
	__enable_irq();
}

void bai_soft_delay(int ms)
{
	unsigned long	last = sloop_get_tick();

	last += ms;
	if (ms > 0) {
		while (sloop_get_tick() < last) {
			sloop_dispatch();
		}
	}
}

void bai_hard_delay(int ms)
{
	HAL_Delay(ms);
}

void *bai_get_uart_xtcb(void *huart)
{
	if (console.uart->handler == huart) {
		return &console;
	}
	return NULL;
}

void *bai_get_current_xtcb(void)
{
	void	*tcb = sloop_get_tcb();	

        if (console.taskid == tcb) {
                return &console;
        }
        return &console;        /* set defaults to console */
}

void *bai_get_default_uart(void)
{
	return &console;
}

int bai_uart_send_sleep(void *uhandle, int ms)
{
	uart_t	*ufp = uhandle;
	unsigned long	last = sloop_get_tick();

	last += ms;
	while (ufp->state & FCMD_SEND) {
		sloop_dispatch();
		if ((ms > 0) && (sloop_get_tick() > last)) {
			return -1;	/* timeout */
		}
	}
	return 0;	/* wake up by ISR */
}

void bai_uart_send_awake(void *huart)
{
	xtcb_t	*xtcb = bai_get_uart_xtcb(huart);

	xtcb->uart->state &= ~FCMD_SEND;
}

int bai_uart_receive_sleep(void *uhandle, int ms)
{
	uart_t	*ufp = uhandle;
	unsigned long	last = sloop_get_tick();

	last += ms;
	while (ufp->state & FCMD_RECV) {
		sloop_dispatch();
		if ((ms > 0) && (sloop_get_tick() > last)) {
			return -1;	/* timeout */
		}
	}
	return 0;	/* wake up by ISR */
}

void bai_uart_receive_awake(void *huart, int state)
{
	xtcb_t          *xtcb = bai_get_uart_xtcb(huart);

	if (xtcb->uart->state & FCMD_RECV) {
		if (state < 0) {
			xtcb->uart->state &= ~FCMD_RECV;
		}
	}
}

int board_init(void)
{
	led_t	*l;

	/* initialize the console for user interface */
	console.uartid   = &huart1;
	console.uart     = &conuart;
	console.readline = &conreadln;

	uart_init(console.uart, console.uartid);
	readline_init(console.readline, console.uart);
	cli_init(&console, NULL);
	console.taskid = sloop_task_create(task_commandline, &console, 10, 0, NULL);

	/* initialize the LED driver */
	if ((l = led_open(GPIOG, GPIO_PIN_13)) != NULL) {
		led_pwm_breath(l, 10, 100);
	}
	if ((l = led_open(GPIOG, GPIO_PIN_14)) != NULL) {
                led_pwm_light(l, 10);
        }
	sloop_task_create(led_tick, NULL, 1, 0, NULL);
	task_puts(&console, splash);
	return 0;
}

void panic(void *p)
{ 
	static char  dying[] = { "BOM!!!\r\n" };
        
	if (p == NULL) {
		bai_uart_poll_send(console.uartid, dying, 8);
        }
} 

